image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  ANDROID_SDK_ROOT: "/sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

stages:
  - build

before_script:
  - dotnet --info
  - export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin"
  - yes | sdkmanager --licenses || true
  - sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

build-android-apk:
  stage: build
  tags:
    - docker  # or 'shared' or another available tag in your runner settings
  script:
    - dotnet workload install maui android
    - dotnet restore
    - dotnet publish MAUI_Class_Tracker.csproj -f:net8.0-android -c:Release -r:android-arm64 -p:AndroidPackageFormat=apk -o:publish-android
  artifacts:
    paths:
      - publish-android
    expire_in: 1 day
    when: always
